// Beschreibung und Songtext je Song. Schlüssel = Spotify-ID (oder YouTube-ID bei „nur YouTube“).
// Fehlt ein Feld, wird der Abschnitt nicht angezeigt. Zeilenumbruch = \n, Leerzeile = \n\n.
window.SONGINFO = {
  "1c59KMCgfbtalgtODpC0ZK": {
    "_title": "Fragile Horizons",
    "story": "A monumental sonic journey across shifting sands, forgotten echoes, and fragile boundaries. “Fragile Horizons” merges the haunting atmosphere of Desert Gothic with the raw power of symphonic rock and a grounded Boom Bap hip-hop groove.\n\nThe track opens with a solitary, haunting oboe melody before sinking into dark, operatic baritone verses. The tension builds relentlessly until it erupts into a soaring tenor hook, propelled by a massive male choir, virtuoso electric violin passages, distorted high-gain guitars, and rapid staccato strings.",
    "lyrics": "Endless sand beneath a fading sun,\nTracing all the steps of what we’ve done.\nA quiet storm inside the ancient stone,\nWalking through the desert dust alone.\nShadows stretching long across the floor,\nKnocking at an everlasting door.\n\nThe pulse is waking in the golden clay,\nA roaring current washing doubt away...\nFeel the skies ignite!\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\nTurning into gold!\n\nFootsteps disappear within the haze,\nBroken compass of forgotten days.\nNo illusions left behind the glass,\nWatching every fallen shadow pass.\nRise above the weight of all the fears,\nEchoing across a thousand years.\n\nThe pulse is waking in the golden clay,\nA roaring current washing doubt away...\nTake the wheel and set it free!\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\nTurning into gold!\n\nNo more sorrow in the burning land...\nReaching out to take an open hand.\nAnd now the horizon breaks wide open\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\n\nAcross the sand...\nThe gold survives..."
  },
  "7v2lBbmzgdDDDsIXdad4ms": {
    "_title": "Shadows of my Yesterday",
    "story": "A deep dive into the void that remains when the lights go out. “Shadows of My Yesterday” is a high-octane Heavy Metal Power Ballad that captures the raw intensity of the 80s.",
    "lyrics": "The clock is ticking on the wall\nI’m waiting for the shadows to fall\nThe silence is a heavy sound\nSince you’re no longer around\nI reach for you in the empty air\nBut there’s only coldness everywhere\n\nAnd I can feel the fire start to fade\nLost in the choices that we made\nThe light is growing dim tonight\nI’m losing hope, I’m losing sight!\n\nOh, I miss you! Like the desert misses rain!\nI’m calling out! Your name through the pain!\nA thousand miles, a million tears\nHaunted by the ghost of all these years\nYeah, I’m screaming! To the sky above\nFor one last moment of your love!\n\nThe photographs have turned to grey\nWatching the memories slip away\nI’m walking through this lonely hall\nStill waiting for your final call\nThe world keeps moving, fast and loud\nBut I’m just a face within the crowd\n\nOh, I miss you! Like the desert misses rain!\nI’m calling out! Your name through the pain!\nA thousand miles, a million tears\nHaunted by the ghost of all these years\nYeah, I’m screaming! To the sky above\nFor one last moment of your love!"
  },
  "5CZwr6ueP4E8fCGbl7W4mn": {
    "_title": "Toxic Devotion",
    "story": "With a slow, gritty groove and soulful male vocals, this track captures the raw emotion of “melting” into a toxic connection. From intimate, breathy verses to a powerful, anthemic chorus, “Toxic Devotion” is a journey through the shadows of the heart.",
    "lyrics": "Smoke is curling ‘round the edge of the bed\nEvery word you whispered, a fever in my head\nIt’s a beautiful poison, a sweet kind of ache\nI know I’m falling for every mistake\nYour skin is a map that leads nowhere good\nBut I’d follow the shadows just like I should\n\nThe air is getting thick, the walls are closing in\nI can feel the nectar dripping on my skin\nI’m losing my grip, I’m losing the fight...\n\nOh, let me dissolve in the heat of your flame\nI’m addicted to the way you call out my name\nIt’s a toxic love, a beautiful mess\nSinking down deep in your velvet caress\nBreak me down, pull me under the tide\nThere’s nowhere left for my spirit to hide\n\nMidnight nectar, a bitter-sweet taste\nGiving my soul to a beautiful waste\nThe danger is humming beneath your touch\nI never knew I could want you this much\nTracing the scars that you left on my heart\n\nOh, let me dissolve in the heat of your flame\nI’m addicted to the way you call out my name\nIt’s a toxic love, a beautiful mess\nSinking down deep in your velvet caress\nBreak me down, pull me under the tide\nThere’s nowhere left for my spirit to hide\n\nI’m melting... I’m fading away...\nIn the glow of the wreckage, I’m begging to stay\nJust one more hit, just one more sin\nLet the ghost of your hunger begin!\n\nSo beautiful...\nLet me dissolve..."
  },
  "2QULAXmGPUAPvkfDpXwDTR": {
    "_title": "Aftermath",
    "story": "Tracing lines in the dust of what’s left. “Aftermath” is a raw exploration of the wreckage left behind by “porcelain lies.” It’s a journey through the static hum of silence and the realization that some kingdoms are built on hollow thrones. It’s about the moment you stop fighting the ghost and start standing tall in the ruins.\n\nMusically, this Cinematic Acoustic Power Ballad is built on a foundation of intimate, breathy verses and a soulful male tenor. It features a dynamic slow-build, starting with a melancholy grand piano and acoustic guitar, eventually escalating into a massive, anthemic orchestral chorus. No growls, just clear, powerful high notes and swelling strings that capture the epic scale of emotional release.",
    "lyrics": "The static hum of a silent phone\nA kingdom built on a hollow throne\nI’m tracing lines in the dust you left\nA slow surrender, a quiet theft\nYou said the truth would set us free\nBut now it’s just a ghost of me.\n\nAnd we’re falling through the gray again\nWaiting for the sky to bend\nEvery promise was a porcelain lie\nI watched it shatter, I watched it die\nNo more words, no more hollow fears\nJust the silence after all these years.\n\nThe clock is ticking but the hands are tied\nNowhere left for the heart to hide\nI memorized the way you looked away\nA thousand colors turning into gray\nWe played the part, we paid the price\nFor walking on such thin, cold ice.\n\nMaybe the fire was meant to burn out\nMaybe the faith was just dressed up in doubt\nI’m letting go of the ghost in the hall\nI’m standing tall, just to watch it all fall!\n\nAnd we’re falling through the gray again\nWaiting for the sky to bend\nEvery promise was a porcelain lie\nI watched it shatter, I watched it die\nNo more words, no more hollow fears\nJust the silence after all these years!\n\nSome roads lead to nowhere...\nSome scars never fade...\nJust a shadow...\nOf the debt we paid."
  },
  "rxjvsiwowFE": {
    "_title": "If My Heart Could Speak",
    "story": "If my heart could speak, it would scream your name! This track is raw, emotional, and built to be played loud.\n\nA YouTube exclusive: this song is not available on Spotify, YouTube Music, Amazon or any other streaming platform. If you want to experience it, YouTube is the place.",
    "lyrics": "The silence falls like heavy rain,\nI try to find the words in vain.\nI stand before you, strong and still,\nAgainst my own unspoken will.\n\nBut deep inside the walls give way,\nThere’s so much more than I can say!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\nIf my heart could speak!\n\nOhhh-oh! Burning like a fire!\nOhhh-oh! Can you feel it rising higher?!\n\nI locked the secrets in the dark,\nAnd tried to hide the burning spark.\nA warrior without a shield,\nUpon this lonely battlefield.\n\nBut deep inside the walls give way,\nThere’s so much more than I can say!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\nIf my heart could speak!\n\nOhhh-oh! Burning like a fire!\nOhhh-oh! Can you feel it rising higher?!\n\nNo lies! No masks! Just open wide!\nThe rhythm of the love I hide!\nCan you hear it beating?!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\n\nIf my heart could speak! (It would scream your name!)\nYeah! I’d write my love across the skies! (Love across the skies!)\n\nIt would say... I love you."
  },
  "3N6ymNEVeNwMvv3WlW8c4s": {
    "_title": "Rising",
    "story": "Walking on the edge of silent lines. “Rising” is a journey from the heavy stone of the past into the open sky. It’s the story of breaking every chain, leaving the shadows behind, and finally tearing down the fear that holds us down.\n\nMusically, the track fuses the driving power of modern metal with uplifting electronic beats. It builds from a tense, atmospheric verse into a massive, arena-sized chorus—exploding not in anger, but in pure energy. It captures the moment you stop falling and start flying.",
    "lyrics": "Walking on the edge of silent lines\nWait for signs\nLeave the past behind\nEvery step feels heavy on the stone\nBuilding castles on my own\nSo afraid of the unknown\nAnd the walls are getting higher\nBut I’m walking through the fire\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\nTearing down the sky\n\nShadows try to pull me to the ground\nBut I won't ever turn around, I love the glory that I found\nI was frozen in the heavy, heavy rain\nNow I'm breaking every chain\nWashing off the stain\nAnd the walls were getting higher\nNow I am the fire!\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\n\nI won't let gravity hold me\nNo, I won't let the shadows own me\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\n\nTearing down the sky"
  }
};
