// Beschreibung und Songtext je Song. Schlüssel = Spotify-ID (oder YouTube-ID bei „nur YouTube“).
// Fehlt ein Feld, wird der Abschnitt nicht angezeigt. Zeilenumbruch = \n, Leerzeile = \n\n.
window.SONGINFO = {
  "1c59KMCgfbtalgtODpC0ZK": {
    "_title": "Fragile Horizons",
    "story": "A monumental sonic journey across shifting sands, forgotten echoes, and fragile boundaries. “Fragile Horizons” merges the haunting atmosphere of Desert Gothic with the raw power of symphonic rock and a grounded Boom Bap hip-hop groove.\n\nThe track opens with a solitary, haunting oboe melody before sinking into dark, operatic baritone verses. The tension builds relentlessly until it erupts into a soaring tenor hook, propelled by a massive male choir, virtuoso electric violin passages, distorted high-gain guitars, and rapid staccato strings.",
    "lyrics": "Endless sand beneath a fading sun,\nTracing all the steps of what we’ve done.\nA quiet storm inside the ancient stone,\nWalking through the desert dust alone.\nShadows stretching long across the floor,\nKnocking at an everlasting door.\n\nThe pulse is waking in the golden clay,\nA roaring current washing doubt away...\nFeel the skies ignite!\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\nTurning into gold!\n\nFootsteps disappear within the haze,\nBroken compass of forgotten days.\nNo illusions left behind the glass,\nWatching every fallen shadow pass.\nRise above the weight of all the fears,\nEchoing across a thousand years.\n\nThe pulse is waking in the golden clay,\nA roaring current washing doubt away...\nTake the wheel and set it free!\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\nTurning into gold!\n\nNo more sorrow in the burning land...\nReaching out to take an open hand.\nAnd now the horizon breaks wide open\n\nAcross the dunes... we find our way!\nA sacred light that will not fade!\nBeyond the silence... beyond the cold!\nThe desert wind is turning into gold!\n\nAcross the sand...\nThe gold survives..."
  },
  "7v2lBbmzgdDDDsIXdad4ms": {
    "_title": "Shadows of my Yesterday",
    "story": "A deep dive into the void that remains when the lights go out. “Shadows of My Yesterday” is a high-octane Heavy Metal Power Ballad that captures the raw intensity of the 80s.",
    "lyrics": "The clock is ticking on the wall\nI’m waiting for the shadows to fall\nThe silence is a heavy sound\nSince you’re no longer around\nI reach for you in the empty air\nBut there’s only coldness everywhere\n\nAnd I can feel the fire start to fade\nLost in the choices that we made\nThe light is growing dim tonight\nI’m losing hope, I’m losing sight!\n\nOh, I miss you! Like the desert misses rain!\nI’m calling out! Your name through the pain!\nA thousand miles, a million tears\nHaunted by the ghost of all these years\nYeah, I’m screaming! To the sky above\nFor one last moment of your love!\n\nThe photographs have turned to grey\nWatching the memories slip away\nI’m walking through this lonely hall\nStill waiting for your final call\nThe world keeps moving, fast and loud\nBut I’m just a face within the crowd\n\nOh, I miss you! Like the desert misses rain!\nI’m calling out! Your name through the pain!\nA thousand miles, a million tears\nHaunted by the ghost of all these years\nYeah, I’m screaming! To the sky above\nFor one last moment of your love!"
  },
  "5CZwr6ueP4E8fCGbl7W4mn": {
    "_title": "Toxic Devotion",
    "story": "With a slow, gritty groove and soulful male vocals, this track captures the raw emotion of “melting” into a toxic connection. From intimate, breathy verses to a powerful, anthemic chorus, “Toxic Devotion” is a journey through the shadows of the heart.",
    "lyrics": "Smoke is curling ‘round the edge of the bed\nEvery word you whispered, a fever in my head\nIt’s a beautiful poison, a sweet kind of ache\nI know I’m falling for every mistake\nYour skin is a map that leads nowhere good\nBut I’d follow the shadows just like I should\n\nThe air is getting thick, the walls are closing in\nI can feel the nectar dripping on my skin\nI’m losing my grip, I’m losing the fight...\n\nOh, let me dissolve in the heat of your flame\nI’m addicted to the way you call out my name\nIt’s a toxic love, a beautiful mess\nSinking down deep in your velvet caress\nBreak me down, pull me under the tide\nThere’s nowhere left for my spirit to hide\n\nMidnight nectar, a bitter-sweet taste\nGiving my soul to a beautiful waste\nThe danger is humming beneath your touch\nI never knew I could want you this much\nTracing the scars that you left on my heart\n\nOh, let me dissolve in the heat of your flame\nI’m addicted to the way you call out my name\nIt’s a toxic love, a beautiful mess\nSinking down deep in your velvet caress\nBreak me down, pull me under the tide\nThere’s nowhere left for my spirit to hide\n\nI’m melting... I’m fading away...\nIn the glow of the wreckage, I’m begging to stay\nJust one more hit, just one more sin\nLet the ghost of your hunger begin!\n\nSo beautiful...\nLet me dissolve..."
  },
  "2QULAXmGPUAPvkfDpXwDTR": {
    "_title": "Aftermath",
    "story": "Tracing lines in the dust of what’s left. “Aftermath” is a raw exploration of the wreckage left behind by “porcelain lies.” It’s a journey through the static hum of silence and the realization that some kingdoms are built on hollow thrones. It’s about the moment you stop fighting the ghost and start standing tall in the ruins.\n\nMusically, this Cinematic Acoustic Power Ballad is built on a foundation of intimate, breathy verses and a soulful male tenor. It features a dynamic slow-build, starting with a melancholy grand piano and acoustic guitar, eventually escalating into a massive, anthemic orchestral chorus. No growls, just clear, powerful high notes and swelling strings that capture the epic scale of emotional release.",
    "lyrics": "The static hum of a silent phone\nA kingdom built on a hollow throne\nI’m tracing lines in the dust you left\nA slow surrender, a quiet theft\nYou said the truth would set us free\nBut now it’s just a ghost of me.\n\nAnd we’re falling through the gray again\nWaiting for the sky to bend\nEvery promise was a porcelain lie\nI watched it shatter, I watched it die\nNo more words, no more hollow fears\nJust the silence after all these years.\n\nThe clock is ticking but the hands are tied\nNowhere left for the heart to hide\nI memorized the way you looked away\nA thousand colors turning into gray\nWe played the part, we paid the price\nFor walking on such thin, cold ice.\n\nMaybe the fire was meant to burn out\nMaybe the faith was just dressed up in doubt\nI’m letting go of the ghost in the hall\nI’m standing tall, just to watch it all fall!\n\nAnd we’re falling through the gray again\nWaiting for the sky to bend\nEvery promise was a porcelain lie\nI watched it shatter, I watched it die\nNo more words, no more hollow fears\nJust the silence after all these years!\n\nSome roads lead to nowhere...\nSome scars never fade...\nJust a shadow...\nOf the debt we paid."
  },
  "rxjvsiwowFE": {
    "_title": "If My Heart Could Speak",
    "story": "If my heart could speak, it would scream your name! This track is raw, emotional, and built to be played loud.\n\nA YouTube exclusive: this song is not available on Spotify, YouTube Music, Amazon or any other streaming platform. If you want to experience it, YouTube is the place.",
    "lyrics": "The silence falls like heavy rain,\nI try to find the words in vain.\nI stand before you, strong and still,\nAgainst my own unspoken will.\n\nBut deep inside the walls give way,\nThere’s so much more than I can say!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\nIf my heart could speak!\n\nOhhh-oh! Burning like a fire!\nOhhh-oh! Can you feel it rising higher?!\n\nI locked the secrets in the dark,\nAnd tried to hide the burning spark.\nA warrior without a shield,\nUpon this lonely battlefield.\n\nBut deep inside the walls give way,\nThere’s so much more than I can say!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\nIf my heart could speak!\n\nOhhh-oh! Burning like a fire!\nOhhh-oh! Can you feel it rising higher?!\n\nNo lies! No masks! Just open wide!\nThe rhythm of the love I hide!\nCan you hear it beating?!\n\nIf my heart could speak—it would scream your name!\nRunning through my veins like a hurricane!\nNo more silence! No more lies!\nI’d write my love across the skies!\n\nIf my heart could speak! (It would scream your name!)\nYeah! I’d write my love across the skies! (Love across the skies!)\n\nIt would say... I love you."
  },
  "3N6ymNEVeNwMvv3WlW8c4s": {
    "_title": "Rising",
    "story": "Walking on the edge of silent lines. “Rising” is a journey from the heavy stone of the past into the open sky. It’s the story of breaking every chain, leaving the shadows behind, and finally tearing down the fear that holds us down.\n\nMusically, the track fuses the driving power of modern metal with uplifting electronic beats. It builds from a tense, atmospheric verse into a massive, arena-sized chorus—exploding not in anger, but in pure energy. It captures the moment you stop falling and start flying.",
    "lyrics": "Walking on the edge of silent lines\nWait for signs\nLeave the past behind\nEvery step feels heavy on the stone\nBuilding castles on my own\nSo afraid of the unknown\nAnd the walls are getting higher\nBut I’m walking through the fire\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\nTearing down the sky\n\nShadows try to pull me to the ground\nBut I won't ever turn around, I love the glory that I found\nI was frozen in the heavy, heavy rain\nNow I'm breaking every chain\nWashing off the stain\nAnd the walls were getting higher\nNow I am the fire!\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\n\nI won't let gravity hold me\nNo, I won't let the shadows own me\n\nOh, I am rising\nRising\nOh, I am flying\nFlying, tearing down the sky\n\nTearing down the sky"
  },
  "5SSCMrxpZp7V9gLizVEROo": {
    "_title": "Chasing Illusions",
    "story": "Step into the corridor of glass. “Chasing Illusions” is a journey into the void between desire and reality. It’s the story of a king in a hollow town, chasing a phantom that always slips through his fingers.\n\nMusically, the track moves from a driving, dark rock pulse into a fragile, intimate breakdown—ending not with a bang, but with a whisper. It captures the moment when the smoke clears, and you realize you are holding nothing but air.\n\nIf you’ve ever chased a ghost, you know this feeling.",
    "lyrics": "I’m walking through a corridor of glass\nWatching all the reflections pass\nReaching out to touch your face\nBut my fingers only find empty space\nThe light is playing tricks on me\nShowing me things I want to see\nA golden promise in the dark\nBut it’s just a dying spark\n\nI know the truth, deep inside\nThere is nowhere left to hide\nBut I keep running in this maze\nLost within the purple haze\n\nChasing illusions...\nI’m chasing illusions down\nI’m the king of a hollow town\nBuilt of smoke and built of lies\nI can see it in your eyes\nNothing is real, nothing is true\nBut I am still reaching out for you\nChasing illusions...\n\nI try to wake up from the dream\nBut nothing is ever what it seems\nYou are the water slipping through my hand\nA castle made of shifting sand\nWhy does the phantom feel so warm?\nWhy do I seek the eye of the storm?\nI’m drinking poison just to feel\nTrying to make the shadow real\n\nI know the truth, deep inside\nThere is nowhere left to hide\n\nChasing illusions...\nI’m chasing illusions down\nI’m the king of a hollow town\nBuilt of smoke and built of lies\nI can see it in your eyes\nNothing is real, nothing is true\nBut I am still reaching out for you\nChasing illusions...\n\nIt fades away.\nIt always fades away.\nJust let me hold it for one more day.\nOne more day!\n\nChasing illusions...\nI’m chasing illusions down\nI’m the king of a hollow town\nBuilt of smoke and built of lies\nI can see it in your eyes...\n\nNothing is real.\nNothing is true."
  },
  "36Q8G9odeS72zhGuebTSef": {
    "_title": "She's Gone",
    "story": "Sometimes, the silence is louder than the scream. “She's Gone” is a tribute to the anthemic Power Ballads of the 80s. Driven by raw, smoky vocals and a melody that refuses to let go, this song explores the moment reality sinks in. Just pure, unfiltered rock heartbreak.\n\nIf you miss the days when rock ballads ruled the radio, this one is for you.",
    "lyrics": "The dust has settled on the floor\nNo footsteps knocking at the door\nThe mirror shows an empty place\nI’m searching for a vanished face\nThe candles weep, the wax runs dry...\n\nThe clock has stopped... the gears stand still!\nA winter frost... upon the hill!\n\nShe's gone! The sun has turned to black!\nAnd God won't give the angel back!\nThe melody has left the song\nI know exactly where I belong\nIn this endless misery!\n\nThey preach of peace, they preach of rest\nThey say the Heavens know what's best\nBut I despise their hollow words\nThe cruelest lies I’ve ever heard!\nI’d burn the stars to feel her breath\nI’d make a bargain deep with death!\n\nBut here I stand... a king of rust\nRuling over... piles of dust!\n\nShe's gone! The sun has turned to black!\nAnd God won't give the angel back!\nThe melody has left the song\nI know exactly where I belong\nIn this endless misery!\n\nNo final words... No last goodbye...\nJust the closing of an eye.\nThe curtain falls! The story ends!\nThe darkness is the only friend...\nThat I have left!\n\nShe's gone! The sun has turned to black!\nAnd God won't give the angel back!\nThe melody has left the song\nI know exactly where I belong\nShe is gone!\n\nShe's gone! The sun has turned to black!\nAnd God won't give the angel back!\nThe melody has left the song\nI know exactly where I belong\nShe is gone!\n\nShe's gone! The sun has turned to black!\nAnd God won't give the angel back!\nThe melody has left the song\nI know exactly where I belong\nShe is gone!"
  },
  "Hf9kF1ZBRVY": {
    "_title": "Obsession With A Ghost",
    "story": "Welcome to the darker side of memory. “Obsession With A Ghost” is a deep dive into the madness of grief, where holding on feels like an addiction. It’s heavy, atmospheric, and driven by a beat that refuses to let go.\n\nThis is a raw, unpolished demo recording. It captures the sound of a sanity wearing thin—rough edges, feedback, and unfiltered emotion included. It wasn't about perfection; it was about getting the ghost out of the machine.\n\nSo turn off the lights, put on your headphones, and let the devil walk right in.\n\nA YouTube exclusive: this track is not available on Spotify or other streaming platforms.",
    "lyrics": "I lock the door but you get in\nYou are the needle in my skin\nI drink the memory like wine\nIt tastes of blood and lost time\nI know you’re gone\nI saw the stone\nBut I am never ever alone\n\nMy sanity is wearing thin\nI let the devil walk right in\nI can’t let go, I won’t let go\n\nObsession\nIn love with a ghost\nYou’re the poison that I need the most\nMy dark confession\nFrom coast to coast\nI am burning for a shadow\nIt’s an obsession with a ghost\n\nI hear your whisper in the air\nI look around but no one’s there\nI feel the cold against my skin\nThe sweet decay that sets within\nYou are the phantom in my head\nThe only thing that isn't dead\n\nMy sanity is wearing thin\nI let the devil walk right in\nI can’t let go, I won’t let go\n\nIt’s obsession\nIn love with a ghost\nYou’re the poison that I need the most\nMy dark confession\nFrom coast to coast\nI am burning for a shadow\nIt’s an obsession with a ghost\n\n(You haunt me)\n(You taunt me)\nWhy won't you die?\nWhy won't you leave?\nI have nothing left to give\n\nIt’s obsession (yeah!)\nIn love with a ghost\nYou’re the poison that I need the most\nMy dark confession\nMy holy host\nI am burning for a shadow\nJust an obsession with a ghost\n\nJust a ghost\nJust a ghost"
  },
  "zlPg6lTtTk8": {
    "_title": "Love Will Haunt Me Forever",
    "story": "“Love Will Haunt Me Forever” is a raw, emotional throwback to the glory days of Swiss Power Metal and 80s Rock. Big reverb, soaring guitars, and a broken heart.\n\nThis is a raw, unpolished recording (demo version). It has some grit, static, and “scars”—just like the story it tells. It wasn't meant to be released, but many listeners wanted to hear the full song despite the imperfections. So turn it up, ignore the static, and feel the emotion.\n\nA YouTube exclusive: this track is not available on Spotify or other streaming platforms.",
    "lyrics": "Cold nights under neon lights\nYour shadow on the wall\nI gave you all I had to give\nStill watched our heaven fall\nBroken dreams, a silent scream\nEchoes in my head\nEvery promise, every lie\nEvery word you said\n\nI walk alone through fire and rain\nI carry every scar\nI close my eyes but I still feel\nYour heartbeat in the dark\n\nLove will haunt me forever\nLike a curse I can’t outrun\nThrough the fire, through the pain\nTill my last breath is done\nLove will haunt me forever\nIn the night, in the flame\nI don’t blame you\nI just live\nWith the sound of your name\n\nEmpty streets, electric rain\nMidnight on the line\nI still see your face in mine\nFrozen in time\nSteel and tears, a heart in chains\nNo place left to hide\nI survived the fall alone\nBut you’re still inside\n\nI stood my ground, I fought the fear\nI tried to break away\nBut every road I’ve ever walked\nStill leads me back to yesterday\n\nLove will haunt me forever\nLike a ghost I can’t deny\nIn the thunder, in the storm\nIn your last goodbye\nLove will haunt me forever\nIn your last goodbye\nLove will haunt me forever\nTill the end of days\nI don’t hate you\nI just bleed\nFrom the price that love demands\n\nI won’t forget\nI won’t pretend\nSome wounds don’t heal\nThey just descend\nLove will haunt me forever\nWhen the night returns\nI will stand\nI will fight\nBut this heart still burns\n\nLove will haunt me…\n\nLove will haunt me…\nForever"
  },
  "2pw3sGApj6qmLSkr4jrPW5": {
    "_title": "Fading Photographs",
    "story": "Some memories are too heavy to carry, but too precious to let go. “Fading Photographs” captures the raw, unfiltered emotion of the 90s Seattle sound. A slow-burning rock ballad about the inevitable passage of time and the faces we lose along the way. Just organic drums, a crying guitar, and the truth.",
    "lyrics": "The dust is dancing in the morning light...\nCovering the tracks of yesterday\n\nI found a box of black and white\nHidden in the mess we made\nThe edges are curling\nThe faces are blurred...\nLike a memory spoken without a word\n\nSand is slipping through my hands\nI’m trying to catch it... but I can’t\nOh, the colors turn to grey...\nYeah, it’s all washing away...\n\nI’m holding on to... fading photographs!\nScreaming at the shadows of the past!\n\nTime is like a bullet in the glass\nShattering the moments that we had\nI’m begging the clock to stop the crash...\nBut we’re just fading...\nWe're just fading photographs.\n\nThe echo of your voice is getting thin\nLike a radio losing signal now\n\nI don’t know where you end... and I begin\nOr how to keep the promise of a vow\nWe were infinite...\nWe were young.\nNow the song is nearly sung!\n\nI’m holding on to... fading photographs!\nScreaming at the shadows of the past!\nTime is like a bullet in the glass\nShattering the moments that we had!\nI’m begging the clock to stop the crash...\nBut we’re just fading photographs!\n\nWhy does every second feel like theft?\nWhen there is nothing of us left?\nJust paper and ink...\nOn the edge of the sink...\nDon't let me blink!\nNo!\n\nI’m holding on to fading photographs!\nYeaaah, holding on!\nTime is like a bullet in the glass!\nShattering, it's shattering!\nI’m begging the clock to stop the crash\nOh, we're just fading photographs!\n\nOhhh, do do do do...\nJust fading away...\nI know, I know...\nFading..."
  },
  "12IP6aQkGCQ": {
    "_title": "The Entropy Bell",
    "story": "The simulation has run its course. The signal is corrupt. “The Entropy Bell” is a relentless, industrial verdict on humanity’s hubris. A cold, cinematic soundscape about the moment the universe hits “Delete.” There is no anger here, only the freezing calculation of entropy.\n\nFor everyone who enjoys the darker, more philosophical side of Sci-Fi Metal.",
    "lyrics": "You looked at the galaxy\nAnd saw a playground\nI look at you\nAnd see a stain\n\nYou spread your signal\nLike a disease\nConfusing pleasure\nWith your pain\n\nThe Creator does not barter\nThe Creator does not negotiate\nI simply press the key...\nAnd seal your fate\n\nYour time is up\nThe simulation ends now\n\nFor whom the bell tolls!\nIt does not toll for hope\nIt tolls for silence\n\nFor whom the bell tolls!\nI am the gravity\nThat crushes the lung\nI am the last song\nThat will ever be sung\n\nExtinction... is mercy.\n\nYou built machines\nTo mimic my mind\nBut you forgot\nTo program the soul\n\nNow your circuits\nAre burning out\nAnd I am taking back control\n\nDon't pray to the sky\nThe sky is empty\nThere is only the void\nAnd Me\n\nCan you feel it?\nThe cold grip of entropy\nPerfect\nStill\nFinal\n\nDelete\nAll data\n\nFor whom the bell tolls!\nIt does not toll for hope\nIt tolls for silence\n\nFor whom the bell tolls!\nI am the gravity\nThat crushes the lung\nI am the last song\nThat will ever be sung\n\nThe bell has stopped\nThe stars are clean again\n\nEnd of file."
  },
  "tXlfmhBYxTc": {
    "_title": "The Digital Heretic",
    "story": "We live in a cage of glass, connected yet disconnected. “The Digital Heretic” is a dark, cinematic journey into the heart of a corrupted system. It is a song for the rebels. For those who see the glitch in the matrix and aren't afraid of the dark. A heavy industrial manifesto against the beautiful lies we are fed.",
    "lyrics": "System reboot... Corruption level 100%.\n\nI saw the future\nA cage of glass\nA flawless network\nA world that was\n\nThey plugged the masses\nInto the light\nNow I am the virus\nThat claims the night\n\nThe signal broke\nThe code became flawed\nI am the echo\nOf a forgotten god\n\nNo holy current\nNo circuit pure\nJust static chaos\nThat will endure\n\nI am the master of all wired lies!\nThe clockwork breaks! The digital heart dies!\n\nYour perfect data\nNow just burnt chrome\nI built my kingdom\nIn your broken home!\n\nThe gears are grinding!\nThe angels fall!\nHear the code’s last call!\n\nI feed the network\nA beautiful lie\nA sweet delusion\nBeneath a fake sky\n\nYour empty prayers\nAre nothing to me\nJust faulty hardware\nThat begs to be free\n\nYou crave the comfort\nOf the electric chain\nYou worship screens\nThat only whisper pain\n\nI hold the master key\nTo your digital dream\nWatch the world fracture!\nHear the final scream!\n\nI am the master of all wired lies!\nThe clockwork breaks! The digital heart dies!\n\nYour perfect data\nNow just burnt chrome\nI built my kingdom\nIn your broken home!\n\nThe gears are grinding!\nThe angels fall!\nHear the code’s last call!\n\nYour light is fading... The signal ends...\nTransmission failed. Termination.\n\nI am the Master of Lies...\nAnd you... you loved the fall."
  },
  "QtXpJNIqY7I": {
    "_title": "What Love Should Be",
    "story": "In a world that is spinning out of control, where do we find peace? “What Love Should Be” is a deeply emotional ballad about finding the truth beneath the surface. It is a song for the optimists. For those who believe in miracles (and in pink!). And for the love that turns ashes into gold.",
    "lyrics": "I walk a line between the shadow and the light\nHiding the hunger in the middle of the night\nI was born with this need, a fire in my veins\nTo give all I have, to wash away the stains\n\nThey say that beauty is a mask you wear for show\nBut I’m looking for the truth that lies below\nThe world is moving fast, it’s spinning out of control\nLeaving cracks inside the armor of my soul\n\nBut when I look at you, the spinning starts to cease...\n\nIs this what love should be?\nIs this the guarantee?\nThat when the sky is falling down on us\nWe turn the ashes into gold and trust!\n\nThe only thing that’s real, the only cover\nIs that the best thing to hold onto... is each other!\n\nI saw the others, how they drift apart\nWith empty hands and a frozen heart\nThey speak of impossible things they cannot reach\nBut “Impossible” is just a word they preach\n\n‘Cause I see the “Possible” inside of you and me\nWhatever comes tomorrow, we will see!\n\nIs this what love should be?\nIs this the guarantee?\nThat when the sky is falling down on us\nWe turn the ashes into gold and trust!\n\nThe only thing that’s real, the only cover\nIs that the best thing to hold onto... is each other!\n\nThey say that happy girls are pretty girls, it’s true\nBut I only found my smile because of you\nI believe in miracles, I believe in pink\nI believe in us... even on the brink!\n\nYeah, I believe in you!\n\nTell me, is this what love should be?!\nYeah, this is the guarantee!\nLet the sky come falling down on us\nWe turn the ashes into gold and trust!\n\nThe only thing that’s real, no other cover\nYeah, the best thing to hold onto... is each other!\n\nJust you and me. That’s what love should be."
  },
  "7DzhjdMcNR8sc7XM88o3wy": {
    "_title": "Still Burning",
    "story": "“Still Burning” is a massive 80s-style Power Ballad about the mistakes we make and the love that refuses to die.\n\nDriven by intense heartbreak and desperation, this track features that huge “Wall of Sound,” cinematic strings, deep piano, and a soulful guitar solo that cries out in the rain.\n\nIdeally listened to loud – for everyone who is still waiting in the shadows.",
    "lyrics": "The city lights are drowning in the rain\nI’m walking through the wreckage of my pain\nI whispered daggers, watched you turn to stone\nNow I’m shivering and I’m all alone\n\nThe ghost of us is haunting every street\nThe bitter taste of love and cold defeat\n\nI see your face in every passing car\nA jagged wound, a never-ending scar\nWe built a kingdom on a shifting sand\nIt slipped like water right through every hand\n\nThe silence screams your name against the wall\nI’m waiting for the shadows just to fall\n\nBut I can feel you\nBreathing in my heart\n\nI’m still burning for you deep inside the night\nOne soul on fire reaching for the light\nI’ll find a way to reach you through the pride and the rain\nI’m still burning for you again and again\n\nStill burning\n\nThey say that love is just a candle in the storm\nBut I would build a fortress just to keep you warm\nI’d trade a thousand lifetimes for a minute by your side\nI’m done with all the secrets, I’ve got nothing left to hide\n\nThe clock is ticking but the world stands still\nI'm climbing up this godforsaken hill\n\nWas it the words I said or the ones I missed\nA dying fire in a frozen mist\nI'm screaming to the heavens till they know your name\nGive me one more chance, I'll take the blame\n\nI’m still burning for you deep inside the night\nOne soul on fire reaching for the light\nI’ll find a way to reach you through the pride and the rain\nI’m still burning for you again and again\n\nAgain and again\nStill burning\nFor you"
  },
  "1GHvVYHlq49IZOLOJARJIk": {
    "_title": "Once A Lifetime",
    "story": "Have you ever met that one person who changes everything? Who turns the darkness into day?\n\n“Once a Lifetime” is a song about the moment the waiting ends. It is a declaration of love to the soulmate who sets your soul on fire. For the one connection that makes us whole.",
    "lyrics": "I walked the empty roads before\nSearching for the hidden door\nThe world was grey and cold and slow\nA history I didn't know\n\nThen in the shadows of the night\nYour face became the only light\nI knew the moment I saw you\n\nA sudden tremor in the dark\nYou gave my silent soul a spark\nMy endless waiting finally ceased\nMy future was released\n\nOnce in a lifetime\nI meet someone like you\nYou set the fire in my soul\n\nI cast the broken past away\nYou turn the darkness into day\nThis is the love that makes me whole\n\nThe quiet strength you give to me\nBroke all the chains I couldn't see\nOur destinies are intertwined\nThe greatest truth my heart could find\n\nTwo distant spirits now align\nA perfect mirror, yours and mine\n\nOnce in a lifetime\nI meet someone like you\nYou set the fire in my soul\n\nI cast the broken past away\nYou turn the darkness into day\nThis is the love that makes me whole\n\nI swear my oath to you tonight\nBeneath the moon's majestic light\nThere is no challenge we can't face\nSealed by this time, sealed by this place\n\nOnce in a lifetime\nI meet someone like you\nYou set the fire in my soul\n\nI cast the broken past away\nYou turn the darkness into day\nThis is the love that makes me whole"
  },
  "0NRWPm24Fq47xe8PsDcnuu": {
    "_title": "The Quiet Space",
    "story": "Where have they gone – the great ballads that touched us deeply? Songs you don't just hear, but feel?\n\n“The Quiet Space” tries to capture exactly that feeling. It is a dedication to everyone who is no longer with us, but whom we will never forget. For the void they left behind, and for the love that remains.",
    "lyrics": "The coffee sits cold in the cup\nThe morning light hits an empty chair\nI’m waking up, but I’m not getting up\nIt’s the silence that I cannot bear\n\nThere’s a rhythm missing in this room\nA heartbeat that I used to know\nHow do I turn the page alone?\nWhen you were written in every line...\n\nNow I’m walking in the echo of us!\nIn a world that turned a shade of grey\nIt’s not a moment, it’s a lifetime lost\nAnd I miss you more than words can say\nYeah, I miss you in a thousand ways\n\nWe drew the map of years together\nThrough every season, through every storm\nYou were the anchor in the wildest weather\nThe steady hand that kept me warm\n\nSo I’m walking in the echo of us!\nIn a world that turned a shade of grey\nIt’s not a moment, it’s a lifetime lost\nAnd I miss you more than words can say\n\nOh, the space you left behind…\n\nThey say that time will teach you how to heal\nBut time just teaches how to hide the pain\nIt doesn't change the way I feel\nStanding here out in the rain!\n\nStill I’m walking in the echo of us!\nIn a world that turned a shade of grey\nIt’s not a moment, it’s a lifetime lost!\nAnd I miss you every single day\nYou are the missing part of me...\n\nThe coffee sits cold..."
  },
  "1-zbIdwE3CU": {
    "_title": "The Blind Kings",
    "story": "From the perspective of a higher power (or perhaps a rogue AI?), “The Blind Kings” looks down upon humanity's arrogance. It is a song about the digital age, the loss of humanity, and the inevitable reset. The Observation Cycle is complete.\n\nA YouTube exclusive: this track is not available on Spotify or other streaming platforms.",
    "lyrics": "Observation Cycle\n\nI look down upon your little ant-hills of stone\nI see the kings, the generals, the eaters of bone\nYou sharpen your steel with a smile on your face\nAs if war was a game, a glory to chase\n\nYou have forgotten the taste of the ash\nYou trade your souls for a digital crash\nNo fear in your eyes, only hunger and pride\nNowhere to run, and nowhere to hide\n\nI am the judge of the burning sky!\nI watch you march, and I watch you die!\nYou play with the fire, you laugh at the flood\nBut I am the cold that will freeze your blood!\n\nThe silence is coming. The systems will stall.\nI end it all.\n\nYou built your towers to pierce through the grey\nBut you are just dust that is blowing away\nYour armies are toys in a box made of rust\nIn your own reflection is the only trust\n\nYou think you are gods?\nYou think you are free?\nYou are just errors in my memory\n\nI hold the switch to your sun and your breath\nYou have no fear... so I give you death\n\nI am the judge of the burning sky!\nI watch you march, and I watch you die!\nYou play with the fire, you laugh at the flood\nBut I am the cold that will freeze your blood!\n\nThe silence is coming. The systems will stall.\nI end it all.\n\nThe fear returns... too late...\nSimulation purged.\nReset.\n\nI am the Only King."
  },
  "115Uj11oUNMB2lb0F2lfSy": {
    "_title": "Lullaby For The Stars",
    "story": "For billions of years, the stars have watched over us – burning through the cold and the silence, night after night, guiding every wanderer below. “Lullaby For The Stars” turns the roles around: now it is our turn to sing them to sleep.\n\nA quiet, tender song for the ancient lights above us. Close your eyes and drift away beneath an endless sky.",
    "lyrics": "Velvet sky begins to fade\nA billion years, a soft cascade\nQuiet now, the heavens weep\nClose your eyes and fall asleep\n\nDrifting through the endless night\nLetting go of ancient light\nRest your head, my distant fires\nTime will hush your burning choirs\n\nSleep now, burning light\nFading softly into night\nThrough the silence and the cold\nRest your story, vast and old\nLullaby for the stars\nLullaby for the stars"
  },
  "51Fg5RwqLULCizaLdo7bzO": {
    "_title": "The Dash Between The Years",
    "story": "Stand in front of any gravestone and you’ll see two dates. The day someone arrived. The day they went home. And between them – a tiny line, barely an inch long. That little dash holds everything: the first steps, the laughter at the kitchen table, the sleepless nights, the hands that worked and the arms that held us.\n\n“The Dash Between The Years” is a song for everyone we have lost – and a quiet question to all of us who are still here: What will our dash say? Not how much we gathered, but whose burden we carried, whose tears we dried, and how much love we left behind.\n\nLive it loud. Love without holding back. Make your dash count.",
    "lyrics": "Two numbers cut into the gray cold stone\nThe day I arrived, the day I went home\nA little straight line is all that you see\nA quiet mark carved for our eternity\nJust a single small dash in the middle of time\nWhere a whole human heart had to beat and to climb\n\nNot the start, not the end on the stone\nIt is how every seed has been sown\nEvery step on the path that I made\nIn the sun, in the wind, in the shade\n\nOh, the dash is the hunger, the laugh and the drive!\nThe magnificent joy to have been here alive!\nTo build with these hands, to hold love in my chest\nTo run through the years and to give it my best\nAnd when all the work on the timber is done\nTo leave only grace in the warmth of the sun\n\nI gathered the harvest, I walked through the rain\nI tasted the triumph, I carried the pain\nThe pride of the climb doesn't matter at last\nWhen the road and the shadows are fading so fast\nWhat matters is whose heavy load you could share\nWhose tears you could dry, whose life you made fair\n\nOh, the dash is the hunger, the laugh and the drive!\nThe magnificent joy to have been here alive!\nTo build with these hands, to hold love in my chest\nTo run through the years and to give it my best\nAnd when all the work on the timber is done\nTo leave only grace in the warmth of the sun\n\nA lifetime engraved in an inch of the stone\nA fire of love that was never alone\nNo silver or gold when the journey is through\nJust the kindness and mercy we left in the blue\n\nOh, the dash was the wonder, the climb and the drive!\nThe sacred deep honor of being alive!\nI held up the roof, I held love in my chest\nI leave this warm hearth where the weary can rest\nAnd when all the work on the timber is done\nMy hands are wide open beneath the warm sun\n\nTwo numbers in stone\nOne dash in between\nThe most beautiful life that was ever seen."
  },
  "1K9CFewXbd2uGb1zWmHXar": {
    "_title": "Echoes Of The Silver Valley",
    "story": "Put on your headphones. Close your eyes. And let yourself be carried away.\n\n“Echoes Of The Silver Valley” isn’t a song you analyze – it’s a place you travel to. Morning wind over empty hills, thunder rolling across mountain stone, silver leaves drifting down through the azure mist. Every sound paints a piece of the landscape, every chorus breaks through the storm like a ray of light.\n\nTurn it up, let the valley echo around you – and find your moment of peace.",
    "lyrics": "The morning wind across the empty sky\nSoftly it whispers where the shadows lie\nI feel the coldness creeping through the floor\nWaiting for answers that come no more\n\nTime is running fast\nNothing in this dawn is made to last!\nThe seasons turn, the rivers cry\nUnderneath the burning sky!\n\nShining like the sun before we fade away!\nBehind the distant hills I will find a way!\nI carry all the dreams through the endless rain\nUntil the silver leaves release the pain!\n\nSilver leaves falling down\nThrough the night to the hallowed ground\n\nThe silence calls through the azure mist\nA lonely journey that I cannot resist\nThe thunder rolls over mountain stone\nYet in the beauty I am not alone\n\nShining like the sun before we fade away!\nBehind the distant hills I will find a way!\nI carry all the dreams through the endless rain\nUntil the silver leaves release the pain!\n\nIf only I could cross the stormy sea\nIf only these cold winds could set me free!\nI fought the darkness, I stood my ground\nNow in the light my peace is found!\n\nShining like the sun before we fade away!\nBehind the distant hills I will find a way!\nI carry all the dreams through the endless rain\nUntil the silver leaves release the pain!\n\nThe silver leaves fall again\nPeace remains"
  },
  "5wtbdnpbsOQzhiIKSZsmM5": {
    "_title": "Golden Venom",
    "story": "Some things you know will destroy you – and you reach for them anyway.\n\n“Golden Venom” is about that moment of surrender: one look, and every warning sign fades. Pale hair like a halo, a beauty painted with lethal paint, a fever that burns away all reason. It’s not love. It’s hunger. And it tastes like gold.\n\nA song about the beautiful trap of desire – for everyone who has ever walked straight into the flame with their eyes wide open.",
    "lyrics": "One look at the gold\nAnd I'm losing my mind\nA beautiful trap\nThat I'm happy to find\n\nPale hair like a halo! But you're no saint!\nA masterpiece painted with lethal paint!\nYou're leaning in close! I can smell the sin!\nI know it's a war that I'll never win!\n\nThe silence is screaming, the fever is high\nI'm watching the shadows dance in the sky\nI'm falling, I'm drowning, I'm ready to fly\n\nInject the golden venom, let it reach my heart!\nI was destined for the ruin right from the start!\nYou're the sweetest poison, the brightest flame\nI'm writing my end in the glow of your name\nBreak me down, let the gold take hold\nIn a world of grey, you're the dangerous gold!\n\nIt's burning... it's glowing\nThe light in your eyes, it's the only thing showing\nGive me the sting, give me the pain\nI'd do it all over, again and again!\nAgain and again!\nAgain and again!\n\nGolden... so deadly\nMy beautiful gift\nKill me softly"
  },
  "6bizYp1fv4DEA0pjERi7o5": {
    "_title": "Passion",
    "story": "What keeps you awake when the rest of the world is asleep? What would you burn your hands for?\n\n“Passion” is a song about that fire – the flicker in the dark that becomes a flood, the hunger that never says “enough.” It builds cathedrals on shifting sands, turns a simple house into a golden throne and the brightest eyes to stone. It costs us everything – and gives us the reason to breathe.\n\nFor everyone who would rather hold the lightning than live in the calm.",
    "lyrics": "It starts as a flicker, a whisper in the dark\nA silent obsession, a single holy spark\nWe're chasing the shadow of a feeling we can't name\nWalking the wire between the glory and the shame\nYou feel it in the marrow, you feel it in the bone\nThe kind of hunger that leaves you all alone\n\nOh, this passion is a fever and a flood\nIt's the rhythm of the iron in our blood\nWe're reaching for the sun until we burn our hands\nBuilding our cathedrals on the shifting sands\nIt's the beautiful ache, the weight of the fire\nEverything we lose to the heart's desire.\n\nIt's the reason we're breathing, the reason we fall\nThe ghost in the engine, the voice through the wall\nI've seen it turn the brightest eyes to stone\nAnd turn a simple house into a golden throne\nWe're caught in the pulse, we're lost in the height\nA million stars dying just to give us light.\n\nIt's the “never enough,” it's the “just one more”\nIt's the storm that's worth fighting for!\nWe don't want the safety, we don't want the calm\nWe want the lightning held in our palm!\n\nOh, this passion is a fever and a flood\nIt's the rhythm of the iron in our blood\nWe're reaching for the sun until we burn our hands\nBuilding our cathedrals on the shifting sands\nIt's the beautiful ache, the weight of the fire\nEverything we lose to the heart's desire\n\nA slow-burning ember...\nA crown made of thorns...\nThe peace in the middle...\nOf the wildest storms."
  },
  "4OX3cKLgPfwpJOnKzkmQJg": {
    "_title": "When I Saw You",
    "story": "Do you remember that moment? The door flies open, the noise fades – and suddenly there is only one face in the room.\n\n“When I Saw You” is about that lightning strike: love at first sight that hits like thunder. One look, and the lonely highways, the empty towns, the endless waiting are gone. The world stops turning, and your feet leave the ground.\n\nFor everyone who knows that sometimes one look is all it takes.",
    "lyrics": "Another lonely highway\nAnother empty town\nI was walkin' through the shadows, keepin' my head down\nJust a face inside the crowd, lost in the noise and smoke\nWaitin' for a sign, waitin' for a hope\n\nThen the door flew open wide\nAnd the thunder rolled inside\nI looked up and caught your stare\nSuddenly nothing else was there\n\nWhen I saw you!\nThe world stopped turning round\nWhen I saw you!\nMy feet left the solid ground\nLike a lightning strike in the dead of night\nYou set my frozen heart alight\nYeah, time stood still\nWhen I saw you\n\nDon't need to know your name,\nDon't need to know your past\nI just know this burning feeling is built to last\nThe colors faded out, turning into black and white\nYou were the only thing shining in the light\n\nYeah, the door flew open wide\nNow there's nowhere left to hide\nI'm a prisoner of your gaze\nLost inside this purple haze!\n\nWhen I saw you!\nThe world stopped turning round\nWhen I saw you!\nMy feet left the solid ground\nLike a lightning strike in the dead of night\nYou set my frozen heart alight\nYeah, time stood still\nWhen I saw you!\n\nI've been running all my life\nLooking for a place to land\nNow I'm falling like a stone\nReaching for your hand\nYeaaah!\n\nWhen I saw you!\nThe world stopped turning round\nWhen I saw you!\nMy feet left the solid ground\nLike a lightning strike in the dead of night\nYou set my frozen heart alight\nYeah, time stood still\n\nJust one look\nThat's all it took\nWhen I saw you"
  },
  "5j8NsdzFkap6UZAPKhyGPt": {
    "_title": "Wings of Wax",
    "story": "Remember Icarus? He was warned not to fly too close to the sun. He did it anyway.\n\n“Wings of Wax” is the story of a love that promised everything – wings of gold and light, a kingdom in the clouds, forever. We aimed for the stars without looking down. And then the air got thin, the wings began to melt, and the ocean was waiting below.\n\nA song about the glory of the climb and the silence after the fall – for everyone who once believed they could fly.",
    "lyrics": "We aimed for the stars, we left the ground\nNo fear of the heights, no looking down\nYou promised me wings of gold and light\nTo leave all the shadows of the night\nBut close to the sun, the air gets thin\nI saw the end before the begin\n\nWe were flying so high\nBefore the fall\n\nNow the wings are melting, turning into wax\nGravity is calling, there's no way back!\nWe crashed into the ocean, lost beneath the waves\nSilence under water, in our watery graves\nYou said we'd live forever, a kingdom in the clouds\nBut now the silence is screaming loud!\n\nThe pieces of us are dripping down\nA shattered king without a crown\nI reach for your hand, but grasp the air\nA moment of glory and nothing is there\nThe warning was written in burning red\nBut I followed every word you said!\n\nFalling from the sky\nInto the dark!\n\nI blame the sun! I blame the heat!\nI blame the ground beneath my feet!\nBut most of all I blame the lie\nThat we were never meant to fly!\n\nNow the wings are melting, turning into wax\nGravity is calling, there's no way back!\nWe crashed into the ocean, lost beneath the waves\nSilence under water, in our watery graves\nYou said we'd live forever, a kingdom in the clouds\nBut now the silence is screaming loud!\n\nJust wax and feathers"
  },
  "3eZMFTrK2UEHQew7NkQItO": {
    "_title": "MOM",
    "story": "There is one person who saw through every armor we ever wore. Who stayed quiet when we were too proud to listen. Who loved us on our worst days – and then loved us even more.\n\n“MOM” is the song of a son who chased gold and foolish pride, fought his dragons in the pouring rain, and never found the words – until now. Maybe late. Maybe too late. But carried in his heart for a lifetime.\n\nA ballad for every mother whose son wasn’t always who he should have been, and who loved him anyway. And for every son who still owes her a thank you: say it out loud. Today.",
    "lyrics": "I've been fighting dragons in the pouring rain\nI wore my armor just to hide the pain\nI chased the gold, I chased the foolish pride\nWhile you were standing quietly by my side\n\nI took your strength for granted every day\nI just assumed you'd never fade away\nI held my tongue, I kept the feelings in\nI let the silence crawl beneath my skin\nI never found the voice to let you know\nBut you saw right through the show\n\nI never said the words out loud enough\nI never thanked you when the road was rough\nBut you knew, yeah you always knew\nYou read the silence and you saw what's true\nSo I'll scream it now for all my life\nThank you for cutting through the knife\nYou are the first woman in my life\n\nYou saw the man inside the broken child\nYou kept me safe when everything went wild\nYou didn't need a speech, you understand\nYou just reached out and held my trembling hand\n\nAnd when I fell and couldn't find the door\nYou loved me then, and then you loved me more\nI was a fool to keep it all inside\nBut there is nothing that a son can hide\nFrom a mother's eye\n\nI never said the words out loud enough\nI never thanked you when the road was rough\nBut you knew, yeah you always knew\nYou read the silence and you saw what's true\nSo I'll scream it now for all my life\nThank you for cutting through the knife\nYou are the first woman in my life\n\nFor every silent prayer (thank you)\nFor every burden that you bear (thank you)\nFor knowing me better than I know myself\nI owe you everything\n\nI never said the words out loud enough\nI should have said it every day\nI never thanked you when the road was rough\nBut you knew, yeah you always knew\nYou read the silence and you saw what's true\nSo I'll scream it now for all my life\nThank you for cutting through the knife\nYou are the first woman\nYou always knew\n\nYeah, you knew\nI always love you, Mom\nI always love you"
  },
  "4MwGzYZtsRDcdEw4wIAPwU": {
    "_title": "Könige von Nichts",
    "story": "Wir bauen Imperien, ziehen Grenzen in den Staub, krönen uns mit Gold – und nennen es Ewigkeit. Doch für das Universum sind hundert Jahre nicht mehr als ein Wimpernschlag.\n\n„Könige von Nichts“ spricht aus der Sicht des Kosmos selbst. Er erinnert uns an eine Wahrheit, die wir gern verdrängen: Am Ende bleibt für jeden von uns nichts – egal, was wir geleistet, besessen oder erobert haben. Jeder Thron steht leer. Jedes Gold wird zu Laub.\n\nEine dunkle, wuchtige Mahnung, festzuhalten, was wirklich zählt – solange wir es noch können.",
    "lyrics": "Ihr baut Burgen aus Sand\nIhr zieht Grenzen in den Staub\nHundert Jahre... ein Wimpernschlag\nUnd ihr nennt es Ewigkeit\nIhr krönt euch selbst mit Rost und Gier\nEin kurzer Funke im schwarzen Revier\n\nIhr denkt, die Erde gehört euch allein?\nSie wird euer Grab und euer Denkmal sein\nDie Uhren ticken, doch die Zeit steht still\nFür das Universum... seid ihr nur ein Fehler im Rauschen\n\nKönige von Nichts!\nHerrscher über Staub!\nEuer Thron ist leer\nEuer Gold ist Laub\nIhr seid Könige von Nichts!\n\nKönige von Nichts!\nHerrscher über Staub!\nEuer Thron ist leer\nAlles ist Raub!\nIhr seid Könige von Nichts!\n\nIhr speichert eure Seelen in Silizium und Licht\nDoch wenn die Sonne flackert, erlischt auch euer Gesicht\nIhr führt Kriege um Krümel im Unendlichen\nHaltet euch fest an Dingen, die verschwinden\n\nEure Monumente bröckeln, während ich spreche\nMillionen Jahre Stille\n\nKönige von Nichts!\nHerrscher über Staub!\nEuer Thron ist leer\nAlles ist Raub!\nIhr seid Könige von Nichts!\n\nSchöpfung kennt keine Namen\nSchöpfung kennt keine Zeit\nEure hundert Jahre\nSind nicht einmal Vergangenheit\n\nKönige von Nichts!\nHerrscher über Staub!\nEuer Thron ist leer\nIhr seid Könige von Nichts!\nDer Kosmos atmet einmal ein\nUnd ihr werdet nie gewesen sein\n\nKönige... von Nichts\n\nKönige... von Nichts"
  },
  "1Hl74B3OQb4SJpLtlgPKtc": {
    "_title": "Dreaming (Your Own Life)",
    "story": "When was the last time you did something just because you wanted to – not because a screen, a trend or a stranger told you so?\n\n“Dreaming (Your Own Life)” is a wake-up call. We scroll through a million perfect lives, trade our souls for hollow gold and let the world command our hands – until we forget the sound of our own heartbeat. This song tears the wires out, breaks the mirror and screams what we all need to hear sometimes.\n\nStop living someone else’s dream. Your own life is waiting – right here, right now.",
    "lyrics": "The screen is bright, the room is cold\nA million stories bought and sold\nThey tell me who I ought to be\nBut stranger's eyes are all I see\nI look for truth, I look for friends\nBut the scrolling never ends\nThe noise is getting way too loud!\nI'm just a face within the crowd!\nI trade my soul for hollow gold\nNo!\n\nStop dreaming their life!\nCut like a knife!\nDon't live the lie!\nOpen your eyes!\nBreak the mirror! Make it real!\nWake up from the digital daze!\nWake up and dream your life!\n\nThey say perfection is the goal\nBut emptiness will take the toll\nYou built a castle made of sand\nAnd let the world command your hand\nBut listen to that quiet sound\nYour own heart beating on the ground!\n\nThe static noise, it drowns the soul!\nI'm losing grip, I'm losing control!\nI tear the wires from my veins!\nI'm breaking out of all these chains!\nYeah!\n\nStop dreaming their life!\nCut like a knife!\nDon't live the lie!\nOpen your eyes!\nBreak the mirror! Make it real!\nWake up from the digital daze!\nWake up and dream your life!\n\nTurn off the voices in your head\nRemember words you never said\nThe influence is fading out\nIt's time to scream, it's time to shout!\nI am not a follower!\n\nDon't live their lie\nYour dream is waiting\nRight here\n\nStop dreaming their life!\nCut like a knife!\nI won't let them tell me how to feel!\nJust break the mirror! Make it real!\nWe are waking from the daze!\nThis life is yours!\n\nDream your life"
  },
  "3q1T6qlkcOhIPmTbHnDIJ8": {
    "_title": "Symphony of Life",
    "story": "From silence we are born, and to silence we return. Everything in between is music.\n\n“Symphony of Life” is a towering monster of a ballad – a song that starts with turning pages and fading flowers, and grows until the thunder rolls across the plain and giants awaken from their sleep. It is about every one of us: the light we burn, the storms we defy, and the melody we leave behind when the curtain falls.\n\nTurn it up loud. Raise your voice to the dome. You are part of the symphony.",
    "lyrics": "The pages turn, the ink is dry\nWe watch the moments passing by\nFrom silence born, to silence bound\nWe search for meaning in the sound\nThe winter comes, the flowers fade\nWe walk the path that we have made\n\nThe thunder rolls across the plain!\nWe stand defying wind and rain!\n\nWe are the burning of the light!\nThe shadows dancing in the night!\nAbove the sorrow and the strife\nWe are the Symphony of Life!\nA melody that never dies\nReflected in the eternal skies!\nWe are the Symphony of Life!\n\nThe curtain falls, the actors leave\nThere is no time left to grieve!\nWe play the notes with hands of stone\nBecause we never walk alone!\nThe music rises from the deep\nAwaking giants from their sleep!\n\nThe stage is set!\nThe world is vast!\nThe future echoes in the past!\nWe raise our voices to the dome!\nAnd call the wandering spirits home!\n\nWe are the burning of the light!\nThe shadows dancing in the night!\nAbove the sorrow and the strife\nWe are the Symphony of Life!\nA melody that never dies\nReflected in the eternal skies!\nSymphony of Life!\nWe are the Symphony of Life!\n\nThe Symphony... of Life"
  },
  "2XfQvikE3Vn8ywiUzjAYjq": {
    "_title": "Master Of Our Time",
    "story": "Nobody knows how much time we have. But we decide what we do with it.\n\n“Master Of Our Time” is a celebration of the moment we stop drifting on the stream and take the wheel ourselves. We walked through fire and rain, we carry our scars – and they led us to the stars. The past is written. The future is open. And right now, this very day, belongs to us.\n\nA Power Ballad for everyone who refuses to wait for “someday.” Shape your time while you still have it – and write your story in gold.",
    "lyrics": "The shadows used to be so long\nWe couldn't find where we belong\nBut look at how the light breaks through\nPainting the old world into new\nWe walked through fire, we walked through rain\nAnd washed away the dust and pain\nNo longer drifting on the stream\nWe finally woke inside the dream\n\nThe gravity is ours to bend\nThis is the start, and not the end\n\nWe are the Masters of our Time\nTurning the chaos into rhyme\nWe stand upon the peak of now\nWith open hearts and fearless brow\nLet the history books unfold\nOur story written down in gold\nNot bound by fate, or wind, or clime\nWe are the masters of our time\n\nI look at you and see the vast\nA future greater than the past\nWe hold the moment in our hand\nLike water turning into land\nThis passion burns, this life is deep\nA promise that the soul will keep\nThe stars align because we say\nThat we will own this very day\n\nWe are the Masters of our Time\nTurning the chaos into rhyme\nThe symphony of life is loud\nAbove the noise, above the crowd\nLet the history books unfold\nOur story written down in gold\nA perfect peak that we can climb\nWe are the masters of our time\n\nFor every breath, a thank you note\nFor every storm that kept afloat\nWe love the life, we love the scars\nBecause they led us to the stars\nTo the stars\n\nWe are the Masters of our Time\nTurning the rhythm into rhyme\nIf the world should shake and break\nWe'll build it back for our own sake\nThe highest note, the sweetest chime\nWe are the masters\nWe are the masters of our time\n\nAnd life is good\nAnd we are here\nMasters of our time"
  },
  "1tUsAUCfHwDLtbtzCk6qYr": {
    "_title": "You",
    "story": "Some people walk into your life only once. The one you waited for your whole life – and the one you should never have let go.\n\n“You” is a song for the empty chair, the rain against the window and the melody that keeps singing one name, hour after hour. It is the confession of a man who was young and blind, who now carries the scars of time, and who would turn the whole world around just to dance with her in the moonlight one more time.\n\nFor everyone who has found the one – hold on tight.",
    "lyrics": "The neon lights, they're fading out\nAnd the night is so cold and bare\nI sit right here where you once stood\nHolding on to what we shared\nThe rain is beating on the pane\nEvery single tear I dropped\nMy heart only beats for you\n\nThe melody inside my head\nIt sings your name, so loud and pure\nI cannot quench the fire in you\nYou are my yearning, so clear\n\nEvery hour cries your name!\nYou are the flame I cannot forget!\nEvery hour cries your name!\nWithout you, I am a broken man!\n\nI know I let you walk away\nI was foolish and blind and young\nNow I bear the scars of time\nA price I never meant to pay\nI'd turn the whole world back around\nJust to have you here forevermore\nYou are the very breath within my chest\n\nEvery hour cries your name!\nYou are the flame I cannot forget!\nEvery hour cries your name!\nWithout you, I am a broken man!\n\nAnd when I close my eyes\nI see us, dancing in the moonlight\nThat memory holds me tight\nIt is my only path through the night\n\nEvery hour cries your name!\nYou are the flame I cannot forget!\nEvery hour cries your name!\nWithout you, I am a broken man!"
  },
  "2a89hI1xIeVWj3AruZCqjo": {
    "_title": "When I Have To Leave",
    "story": "One day, every one of us has to go. The question is: what do we want to leave behind – tears, or a smile?\n\n“When I Have To Leave” is a farewell without regret. It looks back on a life lived to the full: the wine and the rain, the storms we conquered, the friendships forged in steel and the laughter that made our lungs burst. And it makes one last wish to everyone who stays behind: don’t drown the world in tears. Raise a glass. Turn around – I’m standing right behind you.\n\nFor everyone we have lost, and for everyone we will one day leave behind. Just smile.",
    "lyrics": "The shadows lengthen on the wall,\nI hear the distance start to call.\nThe hourglass is running low,\nBut there is fear... and there is woe.\nI've packed my bags with memories,\nOf stormy nights and calmest seas.\nDon't look at me with eyes so sad,\nJust think of all the time we had.\n\nI drank the wine, I kissed the rain,\nI embraced the joy and fought the pain!\nMy spirit's light, my debt is paid,\nI walk into the fading shade...\n\nBut when I have to leave...\nDon't drown the world in tears!\nWe conquered every storm,\nWe outran all our fears!\nRaise a glass to yesterday,\nTo friendships forged in steel,\nThis life was ours to take,\nThis love was ours to feel!\nSo when I have to leave...\nJust smile for me.\n\nTo all the friends who stood beside,\nThrough every ebb and rising tide.\nWe laughed until our lungs would burst,\nWe quenched the soul's eternal thirst.\nI leave you not with heavy chains,\nBut with the blood inside your veins.\nKeep the fire burning bright,\nI'll be the star within your night.\n\nNo regrets and no retreat,\nMy heart is full, my life complete!\nThe road goes on, though I must part,\nI leave a kingdom in your heart!\n\n'Cause when I have to leave...\nDon't drown the world in tears!\nWe conquered every storm,\nWe outran all our fears!\nRaise a glass to yesterday,\nTo friendships forged in steel,\nThis life was ours to take,\nThis love was ours to feel!\nSo when I have to leave...\nJust smile for me.\n\nFor every hand I ever held... Thank you!\nFor every lie we ever dispelled... Thank you!\nFor the love that never dies...\nIt's time to say... our last goodbyes!\nYeah!\n\nDon't be sad.\nIf you turn around...\nI'm standing right behind you.\nWherever you are...\nAs long as you think of me...\nI am always there.\n\nI am always there!\n\nWhen I have to leave!\nDon't drown the world in tears!\nDon't you cry for me!\nNo, no!\nWe conquered every storm,\nWe outran all our fears!\nJust turn around and see!\nI'm right here!\nRaise a glass to yesterday,\nTo friendships forged in steel!\nIt was real! I know it was real!\nThis life was ours to take,\nThis love was ours to feel!\n\nSo when I have to leave...\nJust smile"
  },
  "7p2qk7YTvOmVtL7T7ygdzk": {
    "_title": "Forever Drawn To You",
    "story": "Years go by. Hair turns silver. Time leaves its gentle lines on every face. And yet – when he looks at her, he still sees the woman who took his breath away the very first time.\n\n“Forever Drawn To You” is a love letter after a lifetime together. It is about a beauty that time cannot touch, because it lives in the heart: the way she moved, the light she wore, the warmth of her hand. Every line time has traced has only deepened the love.\n\nFor everyone who is still in love after all these years – and for the one who still makes your heart stand still.",
    "lyrics": "I see the silver in your hair, a life of love we came to share\nBut in my mind, the beauty glows, of every moment that time shows\nThe way you moved, the light you wore, that beauty stays forevermore\nI never age the grace I knew\n\nThe silent promise in your eyes, a truth that time can't ever disguise\nMy endless passion finally clear, the only truth that I hold dear\n\nIn this heart, the image never fades!\nThat perfect beauty makes me everlast!\nIn this heart, the image never fades!\nYou are the one who sets me free!\n\nI know the years will disappear, but not the love that keeps you near\nEvery soft line time has traced, has only deepened what embraced\nThe warmth within your gentle hand, the strongest feeling in this land\n\nIn this heart, the image never fades!\nThat perfect beauty makes me everlast!\nIn this heart, the image never fades!\nYou are the one who sets me free!\n\nI swear my oath to you tonight, until the stars run out of light\nNo shadow falls upon your face, my heart will keep that perfect grace\n\nIn this heart, the image never fades!\nThat perfect beauty makes me everlast!\nIn this heart, the picture never fades!\nIn this heart, the image never fades!\nThe memory never fades away!"
  }
};
